export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const INIT_ENVIRONMENT = 'INIT_ENVIRONMENT';

export const ADD_ACTIVE_TAG = 'ADD_ACTIVE_TAG';
export const DELETE_ACTIVE_TAG = 'DELETE_ACTIVE_TAG';

export const SET_FOOD_RESULT = 'SET_FOOD_RESULT';