/* FOODS */


export const GET_FOODS = 'GET_FOODS';
export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS';
export const GET_FOODS_FAILURE = 'GET_FOODS_FAILURE';

export const GET_RANDOM_FOOD_CLEAR = 'GET_RANDOM_FOOD_CLEAR';
export const GET_RANDOM_FOOD = 'GET_RANDOM_FOOD';
export const GET_RANDOM_FOOD_SUCCESS = 'GET_RANDOM_FOOD_SUCCESS';
export const GET_RANDOM_FOOD_FAILURE = 'GET_RANDOME_FOOD_FAILURE';

export const GET_FOODS_BY_SCROLL = 'GET_FOODS_BY_SCROLL';
export const GET_FOODS_BY_SCROLL_SUCCESS = 'GET_FOODS_BY_SCROLL_SUCCESS';
export const GET_FOODS_BY_SCROLL_FAILURE = 'GET_FOODS_BY_SCROLL_FAILURE';

export const GET_FOOD_BY_NAME = 'GET_FOOD_BY_NAME';
export const GET_FOOD_BY_NAME_SUCCESS = 'GET_FOOD_BY_NAME_SUCCESS';
export const GET_FOOD_BY_NAME_FAILURE = 'GET_FOOD_BY_NAME_FAILURE';

export const GET_FOODS_BY_TAGS = 'GET_FOODS_BY_TAGS';
export const GET_FOODS_BY_TAGS_SUCCESS = 'GET_FOODS_BY_TAGS_SUCCESS';
export const GET_FOODS_BY_TAGS_FAILURE = 'GET_FOODS_BY_TAGS_FAILURE';

export const GET_FOODS_BY_TAG = 'GET_FOODS_BY_TAG';
export const GET_FOODS_BY_TAG_SUCCESS = 'GET_FOODS_BY_TAG_SUCCESS';
export const GET_FOODS_BY_TAG_FAILURE = 'GET_FOODS_BY_TAG_FAILURE';

export const GET_FOODS_BY_SEARCH = 'GET_FOODS_BY_SEARCH';
export const GET_FOODS_BY_SEARCH_SUCCESS = 'GET_FOODS_BY_SEARCH_SUCCESS';
export const GET_FOODS_BY_SEARCH_FAILURE = 'GET_FOODS_BY_SEARCH_FAILURE';

export const POST_FOODS = 'POST_FOODS';
export const POST_FOODS_SUCCESS = 'POST_FOODS_SUCCESS';
export const POST_FOODS_FAILURE = 'POST_FOODS_FAILURE';

export const UPDATE_FOOD = 'UPDATE_FOOD';
export const UPDATE_FOOD_SUCCESS = 'UPDATE_FOOD_SUCCESS';
export const UPDATE_FOOD_FAILURE = 'UPDATE_FOOD_FAILURE';
/* TAGS */
export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';

export const GET_RANDOM_TAGS = 'GET_RANDOM_TAGS';
export const GET_RANDOM_TAGS_SUCCESS = 'GET_RANDOM_TAGS_SUCCESS';
export const GET_RANDOM_TAGS_FAILURE = 'GET_RANDOM_TAGS_FAILURE';

export const GET_SUGGEST_TAGS = 'GET_SUGGEST_TAGS';
export const GET_SUGGEST_TAGS_SUCCESS = 'GET_SUGGEST_TAGS_SUCCESS';
export const GET_SUGGEST_TAGS_FAILURE = 'GET_SUGGEST_TAGS_FAILURE';

export const POST_TAGS = 'POST_TAGS';
export const POST_TAGS_SUCCESS = 'POST_TAGS_SUCCESS';
export const POST_TAGS_FAILURE = 'POST_TAGS_FAILURE';

/* RAW FUNC */
export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const INIT_ENVIRONMENT = 'INIT_ENVIRONMENT';

export const ADD_ACTIVE_TAG = 'ADD_ACTIVE_TAG';
export const DELETE_ACTIVE_TAG = 'DELETE_ACTIVE_TAG';
